FedSynth
T1->T2
IXI
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/Datasets/IXI/T1_T2__PD/ --name T1_T2_pFLSynth_shared_mapper_3_heteregeneous --gpu_ids 2 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 2 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name ixi --save_folder_name IXI --n_clients 4 --task_name t1_t2
BRATS
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/Datasets/BRATS/T1_T2__FLAIR/ --name T1_T2_pFLSynth_shared_mapper_3_heteregeneous --gpu_ids 0 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 2 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name brats --save_folder_name BRATS --n_clients 4 --task_name t1_t2
MIDAS
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/FedSynth/Datasets/MIDAS/T1_T2/ --name T1_T2_pFLSynth_shared_mapper_3_heteregeneous --gpu_ids 3 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 1 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name midas --save_folder_name MIDAS --n_clients 4 --task_name t1_t2
fastMRI
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/FedSynth/Datasets/OASIS/T1_T2__FLAIR/ --name T1_T2_pFLSynth_shared_mapper_3_heteregeneous --gpu_ids 2 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 2 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name fastmri --save_folder_name OASIS --n_clients 4 --task_name t1_t2

Other tasks
IXI
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/FedSynth/Datasets/IXI/T1_T2__PD/ --name T1_T2_pFLSynth_3_heteregeneous_two_D_contrast_based_true --gpu_ids 2 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 2 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name ixi --save_folder_name IXI --n_clients 4 --task_name t2_pd
BRATS
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/FedSynth/Datasets/BRATS/T1_T2__FLAIR/ --name T1_T2_pFLSynth_3_heteregeneous_two_D_contrast_based_true --gpu_ids 0 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 2 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name brats --save_folder_name BRATS --n_clients 4 --task_name flair_t2
MIDAS
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/FedSynth/Datasets/MIDAS/T1_T2/ --name T1_T2_pFLSynth_3_heteregeneous_two_D_contrast_based_true --gpu_ids 3 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 1 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name midas --save_folder_name MIDAS --n_clients 4 --task_name t2_t1
fastMRI
python3 /auto/data2/odalmaz/FedSynth/3_heteregeneous/fedsynth/test.py --dataroot /auto/data2/odalmaz/FedSynth/Datasets/OASIS/T1_T2__FLAIR/ --name T1_T2_pFLSynth_3_heteregeneous_two_D_contrast_based_true --gpu_ids 2 --dataset_mode aligned --model pix2pix_perceptual_2_D --which_model_netG resnet_adain_between --which_direction AtoB --norm batch --output_nc 1 --input_nc 2 --checkpoints_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/checkpoints/ --last_layer linear --phase test --how_many 10000 --serial_batches --results_dir /auto/data2/odalmaz/FedSynth/3_heteregeneous/results/ --dataset_name fastmri --save_folder_name OASIS --n_clients 4 --task_name t2_flair
