from .base_options import BaseOptions


class TrainOptions(BaseOptions):
    def initialize(self):
        BaseOptions.initialize(self)
        self.parser.add_argument('--display_freq', type=int, default=100, help='frequency of showing training results on screen')
        self.parser.add_argument('--display_single_pane_ncols', type=int, default=0, help='if positive, display all images in a single visdom web panel with certain number of images per row.')
        self.parser.add_argument('--update_html_freq', type=int, default=1000, help='frequency of saving training results to html')
        self.parser.add_argument('--print_freq', type=int, default=100, help='frequency of showing training results on console')
        self.parser.add_argument('--save_latest_freq', type=int, default=5000, help='frequency of saving the latest results')
        self.parser.add_argument('--save_epoch_freq', type=int, default=5, help='frequency of saving checkpoints at the end of epochs')
        self.parser.add_argument('--continue_train', action='store_true', help='continue training: load the latest model')
        self.parser.add_argument('--epoch_count', type=int, default=1, help='the starting epoch count, we save the model by <epoch_count>, <epoch_count>+<save_latest_freq>, ...')
        self.parser.add_argument('--phase', type=str, default='train', help='train, val, test, etc')
        self.parser.add_argument('--which_epoch', type=str, default='latest', help='which epoch to load? set to latest to use latest cached model')
        self.parser.add_argument('--niter', type=int, default=100, help='# of iter at starting learning rate')
        self.parser.add_argument('--niter_decay', type=int, default=100, help='# of iter to linearly decay learning rate to zero')
        self.parser.add_argument('--beta1', type=float, default=0.5, help='momentum term of adam')
        self.parser.add_argument('--lr', type=float, default=0.0002, help='initial learning rate for adam')
        self.parser.add_argument('--no_lsgan', action='store_true', help='do *not* use least square GAN, if false, use vanilla GAN')
        self.parser.add_argument('--lambda_A', type=float, default=10.0, help='weight for cycle loss (A -> B -> A)')
        self.parser.add_argument('--lambda_B', type=float, default=10.0, help='weight for cycle loss (B -> A -> B)')
        self.parser.add_argument('--lambda_identity', type=float, default=0,
                                 help='use identity mapping. Setting lambda_identity other than 0 has an effect of scaling the weight of the identity mapping loss.'
                                 'For example, if the weight of the identity loss should be 10 times smaller than the weight of the reconstruction loss, please set lambda_identity = 0.1')
        self.parser.add_argument('--pool_size', type=int, default=50, help='the size of image buffer that stores previously generated images')
        self.parser.add_argument('--no_html', action='store_true', help='do not save intermediate training results to [opt.checkpoints_dir]/[opt.name]/web/')
        self.parser.add_argument('--lr_policy', type=str, default='lambda', help='learning rate policy: lambda|step|plateau')
        self.parser.add_argument('--lr_decay_iters', type=int, default=50, help='multiply by a gamma every lr_decay_iters iterations')

        self.isTrain = True
        self.parser.add_argument('--perc_layer', type=int, default=2, help='which perc loss')
        self.parser.add_argument('--lambda_perc_VGG', type=float, default=1.0, help='weight for vgg loss')
        self.parser.add_argument('--lambda_perc_D', type=float, default=1.0, help='weight for perceptual discriminator loss')
        self.parser.add_argument('--vgg_layer', type=float, default=2, help='layer of vgg for perc loss')
        self.parser.add_argument('--lambda_adv', type=float, default=1.0, help='weight for adversarial loss')
        self.parser.add_argument('--D_perc_layer', type=int, default=7, help='which layer of D')
        self.parser.add_argument('--VGG_perc_layer', type=int, default=2, help='which layer of VGG')
        self.parser.add_argument('--perc_D', type=int, default=0, help='whether to use perceptual loss based on the discriminator')
        self.parser.add_argument('--perc_D_start', type=int, default=0, help='when to start perceptual loss based on the discriminator')
        self.parser.add_argument('--perc_VGG', type=int, default=0, help='whether to use perceptual loss based on the VGG net')
        self.parser.add_argument('--perc_D_all', type=int, default=1, help='if get features from all layers or not')
        self.parser.add_argument('--perc_VGG_all', type=int, default=1, help='if get features from all layers or not')
        self.parser.add_argument('--D_cond',type=int, default=1,help='if Dis conditional or not')
        self.parser.add_argument('--joint_loss',type=int, default=0,help='later')
        self.parser.add_argument('--pretrained_name', type=str, default='experiment_name', help='name of the experiment. It decides where to store samples and models')
        self.parser.add_argument('--results_pretrained', type=str, default='experiment_name', help='name of the experiment. It decides where to store samples and models')
        self.parser.add_argument('--pix_loss', type=str, default='L1', help='L1 or L2 pixelwise loss')
        self.parser.add_argument('--loss_type', type=str, default='L1', help='L1 or phase')
        self.parser.add_argument('--federated_learning', type=int, default=0, help='1 to use federated learning')
